from .AdminPanel import AdminPanel
from .BasePage import BasePage
from .TestInput import TestInput
from .Search import Search
from .TopPanel import TopPanel
from .UserAuthorization import UserAuthorization
from .UserRegistration import UserRegistration
from .UserAccount import UserAccount
from .UserAccountEdit import UserAccountEdit